### ISSUE TITLE
v1 NPM release

### ISSUE THREAD

**Issue by eezing** [eezing/sqerge#13]
### Tasks
- [x] Support ES Modules for JavaScript migration files #20 
- [x] Limit engine support to Node.js v18.x #14 
- [ ] Push v1 to NPM
